<?php
namespace App\OnlineShopping\Database;

class Language
{
 public static function LanguagesOptions()
 {
  return [
   '1' => 'English',
   '2' => 'French',
   '3' => 'German',
   '4' => 'Spanish',
   '5' => 'Italian',
   '6' => 'Portuguese',
   '7' => 'Russian',
   '8' => 'Japanese',
   '9' => 'Chinese',
   '10' => 'Korean',
   '11' => 'Arabic',
   '12' => 'Hindi',
   '13' => 'Urdu',
   '14' => 'Turkish',
   '15' => 'Dutch',
   '16' => 'Swedish',
   '17' => 'Danish',
   '18' => 'Norwegian',
   '19' => 'Finnish',
   '20' => 'Polish',
   '21' => 'Czech',
   '22' => 'Romanian',
   '23' => 'Greek',
   '24' => 'Hungarian',
   '25' => 'Bulgarian',
   '26' => 'Serbian',
   '27' => 'Croatian',
   '28' => 'Slovak',
   '29' => 'Slovenian',
   '30' => 'Estonian',
   '31' => 'Latvian',
   '32' => 'Lithuanian',
   '33' => 'Macedonian',
   '34' => 'Albanian',
   '35' => 'Maltese',
   '36' => 'Thai',
   '37' => 'Vietnamese',
   '38' => 'Indonesian',
   '39' => 'Malay',
   '40' => 'Burmese',
   '41' => 'Georgian',
   '42' => 'Amharic',
   '43' => 'Swahili',
   '44' => 'Somali',
   '45' => 'Kurdish',
   '46' => 'Persian',
   '47' => 'Pashto',
   '48' => 'Kazakh',
   '49' => 'Uzbek',
   '50' => 'Tajik',
   '51' => 'Turkmen',
   '52' => 'Kyrgyz',
   '53' => 'Mongolian',
   '54' => 'Tibetan',
   '55' => 'Dzongkha',
   '56' => 'Nepali',
   '57' => 'Marathi',
   '58' => 'Bengali',
   '59' => 'Gujarati',
   '60' => 'Punjabi',
   '61' => 'Oriya',
   '62' => 'Assamese',
   '63' => 'Kannada',
   '64' => 'Telugu',
   '65' => 'Malayalam',
   '66' => 'Sinhala',
   '67' => 'Thai',
   '68' => 'Lao',
   '69' => 'Khmer',
   '70' => 'Burmese',
   '71' => 'Tagalog',
   '72' => 'Ilocano',
   '73' => 'Cebuano',
   '74' => 'Hiligaynon',
   '75' => 'Bisaya',
   '76' => 'Waray',
   '77' => 'Ibanag',
   '78' => 'Ilokano',
   '79' => 'Pampango',
   '80' => 'Kapampangan',
   '81' => 'Bicolano',
   '82' => 'Ibanag',
   '83' => 'Ilokano',
   '84' => 'Pampango',
   '85' => 'Kapampangan',
   '86' => 'Bicolano',
   '87' => 'Other',
  ];
 }
}